### ISSUE TITLE
Parser does not support ; to separate statements

### ISSUE THREAD

**Issue by pcardune** [candu/xhpy#1]
Something I always write while debugging it the following:

``` python
import pdb; pdb.set_trace()
```

If I try to do this inside an xhp'd module, the parser fails:

```
"xhpy/xhpy/parser.py", line 62, in advance
xhpy.parser.XHPySyntaxError: Expected '(newline)' at line 61, column 14
```

**Comment by candu** [comment]
Should be fixed by https://github.com/candu/xhpy/commit/6c60eeb6a50dd13171b7c84a7ea22d414a1e5df5.
