### ISSUE TITLE
Parser does not support unicode in element text

### ISSUE THREAD

**Issue by pcardune** [candu/xhpy#2]
Just try the following in a module:

```
print <p>é</p>
```

when importing the module, the parser gives the error:

```
File "xhpy/xhpy/parser.py", line 1417, in tokenize_xhpy
xhpy.parser.XHPySyntaxError: Unknown operator ('\xc3') at line 1, column 9
```

**Comment by candu** [comment]
Should be fixed by https://github.com/candu/xhpy/commit/a0b122180fbb2eef296b15c910cc08153b7fd2cb.
