### ISSUE TITLE
Parser ignores comments, causing unicode encoding issues

### ISSUE THREAD

**Issue by pcardune** [candu/xhpy#3]
This is not that big a deal, but can be problematic in certain more obscure scenarios.  For example, http://www.python.org/dev/peps/pep-0263/ gives comments special meaning for the python interpreter, and if they do not get transfered over to the rewritten program, the output of the program will be different.

For example:

``` python
# coding: utf-8
from xhpy.pylib import *
name = u"André"
print <p>{name}</p>
```

Currently this will print
`<p>AndrÃ©</p>`

because the encoding in the comment at the top is not being carried over to the rewritten python file.  What you should get is just
`<p>André</p>`

**Comment by candu** [comment]
Should be fixed by https://github.com/candu/xhpy/commit/fb0b260087342d745a786f2f90769dc344742ead.
